baseURL = 'https://wayneashleyberry.github.io/blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[markup]
  [markup.highlight]
    style = 'github-dark'
[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[markup.goldmark.renderHooks.image]
  useEmbedded = "fallback"
[markup.goldmark.renderHooks.link]
  useEmbedded = "fallback"